# Slack Bot Configuration
slack:
  bot_token: ${SLACK_BOT_TOKEN}
  app_token: ${SLACK_APP_TOKEN}

# Stats Configuration
stats:
  database_path: "${STATS_DB_PATH:/app/data/stats.db}"

# Stable Diffusion Configuration
stable_diffusion:
  comfyui_path: "/Users/GaryT/Stable Diffusion/ComfyUI/"
  output_path: "/Users/GaryT/Stable Diffusion/ComfyUI/output/"
  default_reference_path: "/Users/GaryT/Documents/Pictures/reference.jpg"
  models:
    realistic: "zavychromaxl_v80-017.safetensors"
    anime: "aamXLAnimeMix_v10-023.safetensors"
    korean: "leosamsHelloworldXL_helloworldXL30-020.safetensors"

# Image Generation Settings
image_generation:
  allowed_extensions: ["jpg", "jpeg", "png", "webp"]
  default_negative_prompt: "blurry, nsfw, lowres"

# Queue Settings
queue:
  estimated_generation_time: 60 # seconds

# Logging Configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
